config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('gerenciador.core.urls')),
    path('admin/', admin.site.urls),
    path('anuncios/', include('gerenciador.anuncios.urls')),
]

gerenciador/anuncios/urls.py
from django.urls import path

from .views import (
    AnuncioCreateView,
    AnuncioDetailView,
    AnuncioUpdateView,
    AnuncioDeleteView,
    AnuncioListView,
    AnuncioReportView,
    ClienteCreateView,
    ClienteDetailView,
    ClienteUpdateView,
    ClienteDeleteView,
    ClienteListView,
)

app_name = 'anuncios'

urlpatterns = [
    path('', AnuncioListView.as_view(), name='anuncio_list'),
    path('relatorios/relacao-anuncios/', AnuncioReportView.as_view(), name='anuncio_report'),
    path('novo/', AnuncioCreateView.as_view(), name='anuncio_create'),
    path('<uuid:pk>/detalhar/', AnuncioDetailView.as_view(), name='anuncio_detail'),
    path('<uuid:pk>/editar/', AnuncioUpdateView.as_view(), name='anuncio_update'),
    path('<uuid:pk>/excluir/', AnuncioDeleteView.as_view(), name='anuncio_delete'),
    path('clientes/', ClienteListView.as_view(), name='cliente_list'),
    path('clientes/novo/', ClienteCreateView.as_view(), name='cliente_create'),
    path('clientes/<uuid:pk>/detalhar/', ClienteDetailView.as_view(), name='cliente_detail'),
    path('clientes/<uuid:pk>/editar/', ClienteUpdateView.as_view(), name='cliente_update'),
    path('clientes/<uuid:pk>/excluir/', ClienteDeleteView.as_view(), name='cliente_delete'),
]

gerenciador/core/urls.py
from django.urls import path

from .views import HomeView

app_name = 'core'


urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

gerenciador/anuncios/models.py
import uuid
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

from .utils import (
    calcula_alcance_anuncio,
    converte_views_em_cliques,
    converte_cliques_em_compartilhamentos,
)


class Cliente(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    nome = models.CharField(max_length=100)

    class Meta:
        db_table = 'cliente'
        ordering = ['nome']

    def __str__(self) -> str:
        """Retorna a representação textual do cliente"""
        return self.nome

    def get_absolute_url(self) -> str:
        """Retorna a url para a página que detalha o cliente"""
        return reverse('anuncios:cliente_detail', kwargs={'pk': self.id})


class Anuncio(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    nome = models.CharField(max_length=200)
    cliente = models.ForeignKey(
        to=Cliente,
        on_delete=models.CASCADE,
        related_name='anuncios'
    )
    data_inicio = models.DateField(verbose_name='data de início')
    data_termino = models.DateField(verbose_name='data de término')
    investimento_diario = models.DecimalField(
        verbose_name='investimento diário',
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(0)]
    )

    class Meta:
        db_table = 'anuncio'
        ordering = ['-data_inicio', '-data_termino']
        verbose_name = 'anúncio'
        verbose_name_plural = 'anúncios'

    def __str__(self) -> str:
        """Retorna a representação textual do anúncio"""
        return self.nome

    def get_absolute_url(self) -> str:
        """Retorna a url para a página que detalha o anúncio"""
        return reverse('anuncios:anuncio_detail', kwargs={'pk': self.id})

    def clean(self) -> None:
        """Realiza validações entre campos do model"""
        if self.data_inicio and self.data_termino and self.data_inicio > self.data_termino:
            raise ValidationError('A data de início não deve ser maior que a data de término do anúncio.')

    @property
    def dias_ativo(self) -> int:
        """Retorna a quantidade de dias que o anúncio ficará ativo"""
        return (self.data_termino - self.data_inicio).days + 1

    @property
    def total_investido(self) -> Decimal:
        """
        Retorna o valor total investido de acordo com a quantidade de
        dias em que o anúncio esteve ativo
        """
        return self.investimento_diario * self.dias_ativo

    @property
    def visualizacoes(self) -> int:
        """Retorna a quantidade máxima de visualizações do anúncio"""
        visualizacoes = calcula_alcance_anuncio(self.total_investido)
        return int(visualizacoes)

    @property
    def cliques(self) -> int:
        """Retorna a quantidade máxima de cliques do anúncio"""
        cliques = converte_views_em_cliques(self.visualizacoes)
        return int(cliques)

    @property
    def compartilhamentos(self) -> int:
        """Retorna a quantidade máxima de compartilhamentos do anúncio"""
        compartilhamentos = converte_cliques_em_compartilhamentos(self.cliques)
        return int(compartilhamentos)

gerenciador/core/models.py
from django.db import models

# Create your models here.

gerenciador/anuncios/forms.py
from django import forms

from .models import Anuncio, Cliente


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = ['nome']


class AnuncioForm(forms.ModelForm):

    class Meta:
        model = Anuncio
        fields = [
            'nome',
            'cliente',
            'data_inicio',
            'data_termino',
            'investimento_diario',
        ]

gerenciador/anuncios/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DetailView, UpdateView, DeleteView
)

from django_filters.views import FilterView
from django_tables2 import SingleTableMixin, SingleTableView

from .filters import AnuncioFilter
from .forms import AnuncioForm, ClienteForm
from .mixins import SuccessMessageDeletionMixin
from .models import Anuncio, Cliente
from .tables import AnuncioTable, ClienteTable


class ClienteCreateView(SuccessMessageMixin, CreateView):
    model = Cliente
    form_class = ClienteForm
    success_message = 'Cliente "%(nome)s" criado com sucesso!'
    template_name = 'anuncios/cliente_create.html'

    def get_success_url(self):
        url = super().get_success_url()
        if 'btn_salvar_e_adicionar_outro' in self.request.POST:
            url = reverse_lazy('anuncios:cliente_create')
        return url


class ClienteDetailView(SingleTableMixin, DetailView):
    model = Cliente
    table_class = AnuncioTable
    template_name = 'anuncios/cliente_detail.html'

    def get_table_data(self):
        return self.object.anuncios.all()

    def get_table_kwargs(self):
        return {'exclude': ('id', 'cliente')}


class ClienteUpdateView(SuccessMessageMixin, UpdateView):
    model = Cliente
    form_class = ClienteForm
    success_message = 'Cliente "%(nome)s" alterado com sucesso!'
    template_name = 'anuncios/cliente_update.html'


class ClienteDeleteView(SuccessMessageDeletionMixin, DeleteView):
    model = Cliente
    form_class = ClienteForm
    success_message = 'Cliente "%(nome)s" excluído com sucesso!'
    success_url = reverse_lazy('anuncios:cliente_list')


class ClienteListView(SingleTableView):
    model = Cliente
    table_class = ClienteTable
    template_name = 'anuncios/cliente_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existem_objetos_cadastrados'] = self.model.objects.exists()
        return context


class AnuncioCreateView(SuccessMessageMixin, CreateView):
    model = Anuncio
    form_class = AnuncioForm
    success_message = 'Anúncio "%(nome)s" criado com sucesso!'
    template_name = 'anuncios/anuncio_create.html'

    def get_success_url(self):
        url = super().get_success_url()
        if 'btn_salvar_e_adicionar_outro' in self.request.POST:
            url = reverse_lazy('anuncios:anuncio_create')
        return url


class AnuncioDetailView(DetailView):
    model = Anuncio
    template_name = 'anuncios/anuncio_detail.html'


class AnuncioUpdateView(SuccessMessageMixin, UpdateView):
    model = Anuncio
    form_class = AnuncioForm
    success_message = 'Anúncio "%(nome)s" alterado com sucesso!'
    template_name = 'anuncios/anuncio_update.html'


class AnuncioDeleteView(SuccessMessageDeletionMixin, DeleteView):
    model = Anuncio
    form_class = AnuncioForm
    success_message = 'Anúncio "%(nome)s" excluído com sucesso!'
    success_url = reverse_lazy('anuncios:anuncio_list')


class AnuncioListView(SingleTableView):
    model = Anuncio
    table_class = AnuncioTable
    template_name = 'anuncios/anuncio_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existem_objetos_cadastrados'] = self.model.objects.exists()
        return context


class AnuncioReportView(FilterView):
    model = Anuncio
    filterset_class = AnuncioFilter
    ordering = ['nome']
    template_name = 'anuncios/anuncio_report.html'

    def get_total_geral(self):
        totais = {
            'investido': 0,
            'visualizacoes': 0,
            'cliques': 0,
            'compartilhamentos': 0,
        }
        for obj in self.object_list:
            totais['investido'] += obj.total_investido
            totais['visualizacoes'] += obj.visualizacoes
            totais['cliques'] += obj.cliques
            totais['compartilhamentos'] += obj.compartilhamentos
        return totais

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_geral'] = self.get_total_geral()
        return context

gerenciador/core/views.py
from django.views.generic import TemplateView


class HomeView(TemplateView):
    template_name = 'core/home.html'

gerenciador/templates/base.html
{% load static %}
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

    {% block extrahead %}{% endblock extrahead %}
    {% block stylesheet %}{% endblock stylesheet %}

    <title>{% block title %}Gerenciador de anúncios{% endblock title %}</title>

  </head>
  <body>
    <div class="wrapper">
      {% block sidebar %}{% endblock sidebar %}

      <div class="main">
        {% block main %}

          {% block navbar %}{% endblock navbar %}

          <main class="content mt-3">
            <div class="container">
              {% block breadcrumb %}{% endblock breadcrumb %}
              {% block messages %}{% endblock messages %}
              {% block content %}{% endblock content %}
            </div>
          </main>

          {% block footer %}{% endblock footer %}

        {% endblock main %}
      </div>

    </div>
    {% block javascript %}
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
    {% endblock javascript %}
  </body>
</html>

gerenciador/templates/base_site.html
{% extends "base.html" %}

{% load static %}

{% block stylesheet %}
  {{ block.super }}
  <link href="{% static 'css/base_site.css' %}" rel="stylesheet">
  <link href="{% static 'css/sidebar.css' %}" rel="stylesheet">
{% endblock stylesheet %}


{% block sidebar %}
  <nav id="sidebar">
    <div class="sidebar-content">
      <a class="sidebar-brand" href="{% url 'core:home' %}">
        <img class="rounded-circle bg-white" src="{% static 'img/logo_agencia.png' %}" width="48" height="48" alt="Agência 82">
        <spam class="ms-2">Divulga Tudo</spam>
      </a>
      <ul class="sidebar-nav">
        <li class="sidebar-header">Cadastros</li>
        {% url 'anuncios:cliente_list' as url_clientes %}
        <li class="sidebar-item{% if request.path == url_clientes %} active{% endif %}">
          <a href="{{ url_clientes }}" class="sidebar-link">
            <i class="bi bi-people align-middle"></i>
            <span class="align-middle">Clientes</span>
          </a>
        </li>
        {% url 'anuncios:anuncio_list' as url_anuncios %}
        <li class="sidebar-item{% if request.path == url_anuncios %} active{% endif %}">
          <a href="{{ url_anuncios }}" class="sidebar-link">
            <i class="bi bi-megaphone align-middle"></i>
            <span class="align-middle">Anúncios</span>
          </a>
        </li>
        <li class="sidebar-header">Relatórios</li>
        {% url 'anuncios:anuncio_report' as url_relacao_anuncios %}
        <li class="sidebar-item{% if request.path == url_relacao_anuncios %} active{% endif %}">
          <a href="{{ url_relacao_anuncios }}" class="sidebar-link">
            <i class="bi bi-file-earmark-bar-graph align-middle"></i>
            <span class="align-middle">Relação de Anúncios</span>
          </a>
        </li>
      </ul>
      <div class="sidebar-footer d-none d-lg-block">
        <div class="text-center">
          <div class="media-body">
            <div class="text-muted">
              Versão
              <span>1.0.0</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
{% endblock sidebar %}

{% block navbar %}
  <nav class="navbar navbar-expand navbar-light bg-white">
    <div class="container-fluid">
      <div class="custom-toggle">
        <button id="sidebarCollapser" type="button" class="btn sidebar-toggle">
          <i class="bi bi-list"></i>
        </button>
      </div>
      <span class="navbar-brand h1 mb-0 ms-3 me-auto">
        <img src="{% static 'img/logo_agencia.png' %}" alt="Agência Divulga Tudo" width="48" height="48">
        <strong class="navbar-brand-name">Gerenciador de Anúncios</strong>
      </span>
    </div>
  </nav>
{% endblock navbar %}

{% block messages %}
  {% if messages %}{% for message in messages %}
  <div {% if message.tags %} class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert"{% endif %}>
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
  {% endfor %}{% endif %}
{% endblock messages %}

{% block footer %}
  <footer class="footer mt-auto pt-3">
    <div class="container text-muted text-center">
      <p>Feito com <i class="bi bi-heart-fill"></i> &amp; <a href="https://www.djangoproject.com/"><img src="{% static 'img/django.svg' %}" alt="Django"/></a> por <a href="https://www.linkedin.com/mwlite/in/diogoalvesti" class="text-decoration-none"><strong class="text-reset">Diogo Alves</strong></a>
      </p>
    </div>
  </footer>
{% endblock footer %}

{% block javascript %}
  {{ block.super }}
  <script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
  <script src="{% static 'js/base_site.js' %}"></script>
{% endblock javascript %}