config/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('gerenciador.core.urls')),
    path('admin/', admin.site.urls),
    path('anuncios/', include('gerenciador.anuncios.urls')),
]

gerenciador/anuncios/urls.py
from django.urls import path

from .views import (
    AnuncioCreateView,
    AnuncioDetailView,
    AnuncioUpdateView,
    AnuncioDeleteView,
    AnuncioListView,
    AnuncioReportView,
    ClienteCreateView,
    ClienteDetailView,
    ClienteUpdateView,
    ClienteDeleteView,
    ClienteListView,
)

app_name = 'anuncios'

urlpatterns = [
    path('', AnuncioListView.as_view(), name='anuncio_list'),
    path('relatorios/relacao-anuncios/', AnuncioReportView.as_view(), name='anuncio_report'),
    path('novo/', AnuncioCreateView.as_view(), name='anuncio_create'),
    path('<uuid:pk>/detalhar/', AnuncioDetailView.as_view(), name='anuncio_detail'),
    path('<uuid:pk>/editar/', AnuncioUpdateView.as_view(), name='anuncio_update'),
    path('<uuid:pk>/excluir/', AnuncioDeleteView.as_view(), name='anuncio_delete'),
    path('clientes/', ClienteListView.as_view(), name='cliente_list'),
    path('clientes/novo/', ClienteCreateView.as_view(), name='cliente_create'),
    path('clientes/<uuid:pk>/detalhar/', ClienteDetailView.as_view(), name='cliente_detail'),
    path('clientes/<uuid:pk>/editar/', ClienteUpdateView.as_view(), name='cliente_update'),
    path('clientes/<uuid:pk>/excluir/', ClienteDeleteView.as_view(), name='cliente_delete'),
]

gerenciador/anuncios/models.py
import uuid
from decimal import Decimal

from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse

from .utils import (
    calcula_alcance_anuncio,
    converte_views_em_cliques,
    converte_cliques_em_compartilhamentos,
)


class Cliente(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    nome = models.CharField(max_length=100)

    class Meta:
        db_table = 'cliente'
        ordering = ['nome']

    def __str__(self) -> str:
        """Retorna a representação textual do cliente"""
        return self.nome

    def get_absolute_url(self) -> str:
        """Retorna a url para a página que detalha o cliente"""
        return reverse('anuncios:cliente_detail', kwargs={'pk': self.id})


class Anuncio(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    nome = models.CharField(max_length=200)
    cliente = models.ForeignKey(
        to=Cliente,
        on_delete=models.CASCADE,
        related_name='anuncios'
    )
    data_inicio = models.DateField(verbose_name='data de início')
    data_termino = models.DateField(verbose_name='data de término')
    investimento_diario = models.DecimalField(
        verbose_name='investimento diário',
        max_digits=12,
        decimal_places=2,
        validators=[MinValueValidator(0)]
    )

    class Meta:
        db_table = 'anuncio'
        ordering = ['-data_inicio', '-data_termino']
        verbose_name = 'anúncio'
        verbose_name_plural = 'anúncios'

    def __str__(self) -> str:
        """Retorna a representação textual do anúncio"""
        return self.nome

    def get_absolute_url(self) -> str:
        """Retorna a url para a página que detalha o anúncio"""
        return reverse('anuncios:anuncio_detail', kwargs={'pk': self.id})

    def clean(self) -> None:
        """Realiza validações entre campos do model"""
        if self.data_inicio and self.data_termino and self.data_inicio > self.data_termino:
            raise ValidationError('A data de início não deve ser maior que a data de término do anúncio.')

    @property
    def dias_ativo(self) -> int:
        """Retorna a quantidade de dias que o anúncio ficará ativo"""
        return (self.data_termino - self.data_inicio).days + 1

    @property
    def total_investido(self) -> Decimal:
        """
        Retorna o valor total investido de acordo com a quantidade de
        dias em que o anúncio esteve ativo
        """
        return self.investimento_diario * self.dias_ativo

    @property
    def visualizacoes(self) -> int:
        """Retorna a quantidade máxima de visualizações do anúncio"""
        visualizacoes = calcula_alcance_anuncio(self.total_investido)
        return int(visualizacoes)

    @property
    def cliques(self) -> int:
        """Retorna a quantidade máxima de cliques do anúncio"""
        cliques = converte_views_em_cliques(self.visualizacoes)
        return int(cliques)

    @property
    def compartilhamentos(self) -> int:
        """Retorna a quantidade máxima de compartilhamentos do anúncio"""
        compartilhamentos = converte_cliques_em_compartilhamentos(self.cliques)
        return int(compartilhamentos)

gerenciador/anuncios/forms.py
from django import forms

from .models import Anuncio, Cliente


class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = ['nome']


class AnuncioForm(forms.ModelForm):

    class Meta:
        model = Anuncio
        fields = [
            'nome',
            'cliente',
            'data_inicio',
            'data_termino',
            'investimento_diario',
        ]

gerenciador/anuncios/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView, DetailView, UpdateView, DeleteView
)

from django_filters.views import FilterView
from django_tables2 import SingleTableMixin, SingleTableView

from .filters import AnuncioFilter
from .forms import AnuncioForm, ClienteForm
from .mixins import SuccessMessageDeletionMixin
from .models import Anuncio, Cliente
from .tables import AnuncioTable, ClienteTable


class ClienteCreateView(SuccessMessageMixin, CreateView):
    model = Cliente
    form_class = ClienteForm
    success_message = 'Cliente "%(nome)s" criado com sucesso!'
    template_name = 'anuncios/cliente_create.html'

    def get_success_url(self):
        url = super().get_success_url()
        if 'btn_salvar_e_adicionar_outro' in self.request.POST:
            url = reverse_lazy('anuncios:cliente_create')
        return url


class ClienteDetailView(SingleTableMixin, DetailView):
    model = Cliente
    table_class = AnuncioTable
    template_name = 'anuncios/cliente_detail.html'

    def get_table_data(self):
        return self.object.anuncios.all()

    def get_table_kwargs(self):
        return {'exclude': ('id', 'cliente')}


class ClienteUpdateView(SuccessMessageMixin, UpdateView):
    model = Cliente
    form_class = ClienteForm
    success_message = 'Cliente "%(nome)s" alterado com sucesso!'
    template_name = 'anuncios/cliente_update.html'


class ClienteDeleteView(SuccessMessageDeletionMixin, DeleteView):
    model = Cliente
    form_class = ClienteForm
    success_message = 'Cliente "%(nome)s" excluído com sucesso!'
    success_url = reverse_lazy('anuncios:cliente_list')


class ClienteListView(SingleTableView):
    model = Cliente
    table_class = ClienteTable
    template_name = 'anuncios/cliente_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existem_objetos_cadastrados'] = self.model.objects.exists()
        return context


class AnuncioCreateView(SuccessMessageMixin, CreateView):
    model = Anuncio
    form_class = AnuncioForm
    success_message = 'Anúncio "%(nome)s" criado com sucesso!'
    template_name = 'anuncios/anuncio_create.html'

    def get_success_url(self):
        url = super().get_success_url()
        if 'btn_salvar_e_adicionar_outro' in self.request.POST:
            url = reverse_lazy('anuncios:anuncio_create')
        return url


class AnuncioDetailView(DetailView):
    model = Anuncio
    template_name = 'anuncios/anuncio_detail.html'


class AnuncioUpdateView(SuccessMessageMixin, UpdateView):
    model = Anuncio
    form_class = AnuncioForm
    success_message = 'Anúncio "%(nome)s" alterado com sucesso!'
    template_name = 'anuncios/anuncio_update.html'


class AnuncioDeleteView(SuccessMessageDeletionMixin, DeleteView):
    model = Anuncio
    form_class = AnuncioForm
    success_message = 'Anúncio "%(nome)s" excluído com sucesso!'
    success_url = reverse_lazy('anuncios:anuncio_list')


class AnuncioListView(SingleTableView):
    model = Anuncio
    table_class = AnuncioTable
    template_name = 'anuncios/anuncio_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['existem_objetos_cadastrados'] = self.model.objects.exists()
        return context


class AnuncioReportView(FilterView):
    model = Anuncio
    filterset_class = AnuncioFilter
    ordering = ['nome']
    template_name = 'anuncios/anuncio_report.html'

    def get_total_geral(self):
        totais = {
            'investido': 0,
            'visualizacoes': 0,
            'cliques': 0,
            'compartilhamentos': 0,
        }
        for obj in self.object_list:
            totais['investido'] += obj.total_investido
            totais['visualizacoes'] += obj.visualizacoes
            totais['cliques'] += obj.cliques
            totais['compartilhamentos'] += obj.compartilhamentos
        return totais

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['total_geral'] = self.get_total_geral()
        return context

gerenciador/anuncios/templates/anuncios/_anuncio_form_fields.html
{% load crispy_forms_tags %}

<div class="row">
	{{ form|as_crispy_errors }}
	{{ form.nome|as_crispy_field }}
	{{ form.cliente|as_crispy_field }}
	<div class="col-lg-4">{{ form.data_inicio|as_crispy_field }}</div>
	<div class="col-lg-4">{{ form.data_termino|as_crispy_field }}</div>
	<div class="col-lg-4">{{ form.investimento_diario|as_crispy_field }}</div>
</div>

gerenciador/anuncios/templates/anuncios/anuncio_create.html
{% extends "base_site.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Cadastrar anúncio | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="col-xl-8 mx-auto">
    <div class="card">
      <form method="post">
        {% csrf_token %}
        <div class="card-header p-4">
          <h1 class="mx-4">Cadastrar Anúncio</h1>
        </div>
        <div class="card-body mx-4">
          {% include 'anuncios/_anuncio_form_fields.html' %}
        </div>
        <div class="card-footer d-flex flex-column flex-md-row p-4">
          <button class="btn btn-primary ms-md-2 order-md-3" type="submit">Salvar</button>
          <button class="btn btn-outline-primary mt-2 mt-md-0 order-md-2"
                  type="submit" name="btn_salvar_e_adicionar_outro">Salvar e adicionar outro</button>
          <a class="btn btn-link d-none d-md-block me-auto order-md-1" href="{% url 'anuncios:anuncio_list' %}">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/inputmask.min.js' %}"></script>
  <script src="{% static 'anuncios/js/app.js' %}"></script>
{% endblock javascript %}

gerenciador/anuncios/templates/anuncios/anuncio_detail.html
{% extends "base_site.html" %}

{% load static %}
{% load humanize %}
{% load verbose_name from anuncios_tags %}

{% block title %}Detalhes do anúncio | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="col mb-2">
    <div class="card">
      <div class="card-header p-4">
        <div class="d-flex flex-column flex-lg-row align-items-md-end mx-4">
          <h1 class="card-title me-auto">Detalhes do anúncio</h1>
          <div class="d-flex">
            <div class="flex-fill">
              <a class="btn btn-light btn-block" href="{% url 'anuncios:anuncio_list' %}">
                <i class="bi bi-arrow-left" aria-hidden="true"></i>
                <span>Voltar</span>
              </a>
              <button class="btn btn-outline-danger mx-2" type="button" data-bs-toggle="modal" data-bs-target="#modalDelete"
                title="Excluir" data-bs-url="{% url 'anuncios:anuncio_delete' anuncio.pk %}"
                data-bs-model="{{ anuncio|verbose_name }}" data-bs-object="{{ anuncio }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
              </button>
              <a class="btn btn-primary btn-block" href="{% url 'anuncios:anuncio_update' anuncio.pk %}">
                <i class="bi bi-pencil-square"></i>
                <span>Editar</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body mx-4">
        <table class="table table-sm">
          <tbody>
            <tr>
              <th>Nome</th>
              <td>{{ anuncio.nome }}</td>
            </tr>
            <tr>
              <th>Cliente</th>
              <td>{{ anuncio.cliente }}</td>
            </tr>
            <tr>
              <th>Data de início</th>
              <td>{{ anuncio.data_inicio }}</td>
            </tr>
            <tr>
              <th>Data de término</th>
              <td>{{ anuncio.data_termino }}</td>
            </tr>
            <tr>
              <th>Investimento diário</th>
              <td>R$ {{ anuncio.investimento_diario|intcomma }}</td>
            </tr>
          </tbody>
        </table>
        <div class="py-4">
          <h3>Projeções</h3>
          <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4 text-center">
            <div class="col mb-3">
              <div class="card card-total money rounded-3 shadow-sm h-100">
                <div class="card-body">
                  <h2 class="card-title">R$ {{ anuncio.total_investido|intcomma }}</h2>
                  <p class="card-text">Investido{{ anuncio.total_investido|pluralize }}</p>
                </div>
              </div>
            </div>
            <div class="col mb-3">
              <div class="card card-total views rounded-3 shadow-sm h-100">
                <div class="card-body">
                  <h2 class="card-title">{{ anuncio.visualizacoes|intcomma }}</h2>
                  <p class="card-text">Visualizaç{{ anuncio.visualizacoes|pluralize:"ão,ões" }}</p>
                </div>
              </div>
            </div>
            <div class="col mb-3">
              <div class="card card-total clicks rounded-3 shadow-sm h-100">
                <div class="card-body">
                  <h2 class="card-title">{{ anuncio.cliques|intcomma }}</h2>
                  <p class="card-text">Clique{{ anuncio.cliques|pluralize }}</p>
                </div>
              </div>
            </div>
            <div class="col mb-3">
              <div class="card card-total shares rounded-3 shadow-sm h-100">
                <div class="card-body">
                  <h2 class="card-title">{{ anuncio.compartilhamentos|intcomma }}</h2>
                  <p class="card-text">Compartilhamento{{ anuncio.compartilhamentos|pluralize }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    {% include "includes/modal_confirm_delete.html" %}
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/modalDelete.js' %}"></script>
{% endblock javascript %}

gerenciador/anuncios/templates/anuncios/anuncio_list.html
{% extends "base_site.html" %}

{% load static %}
{% load django_tables2 %}
{% load crispy_forms_tags %}

{% block title %}Lista de anúncios | {{ block.super }}{% endblock %}

{% block content %}
  {% if existem_objetos_cadastrados %}
    <div class="card">
      <div class="card-header p-4">
        <div class="d-flex flex-column flex-lg-row align-items-md-end mx-4">
          <h1 class="card-title me-auto">Anúncios</h1>
          <div class="d-flex">
            <div class="flex-fill">
              <a class="btn btn-primary btn-block" href="{% url 'anuncios:anuncio_create' %}">
                <i class="bi bi-plus-lg" aria-hidden="true"></i>
                <span>Novo Anúncio</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body mx-4">{% render_table table %}</div>
    </div>
  {% else %}
    <div class="p-5 mb-5 bg-transparent text-center">
      <div class="container-fluid py-5">
        <h2 class="jumbotron-heading">Cadastre um novo anúncio</h2>
        <p class="lead text-muted">Está meio vazio aqui... Clique no botão abaixo para cadastrar seu 1º anúncio.</p>
        <a class="btn btn-primary" href="{% url 'anuncios:anuncio_create' %}">
          <i class="bi bi-plus-lg" aria-hidden="true"></i>
          <span>Novo anúncio</span>
        </a>
      </div>
    </div>
  {% endif %}
{% endblock content %}

gerenciador/anuncios/templates/anuncios/anuncio_report.html
{% extends "base_site.html" %}

{% load static %}
{% load humanize %}
{% load crispy_forms_tags %}

{% block title %}Relação de Anúncios - {{ block.super }}{% endblock %}

{% block content %}
  <div class="card card-report">
    <div class="card-header p-4">
      <div class="d-flex flex-column flex-lg-row align-items-md-end mx-4">
        <h1 class="card-title text-nowrap me-auto">Relação de Anúncios</h1>
        <div class="d-flex d-print-none">
          <div class="dropdown flex-fill mr-2 no-print">
            <button type="button" class="btn btn-outline-secondary btn-block" data-bs-toggle="dropdown">
              <i class="bi bi-filter"></i>
              <span>Filtrar</span>
            </button>
            <button type="button" class="btn btn-outline-secondary btn-block ms-2" title="Imprimir" onclick="window.print();">
              <i class="bi bi-printer"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
              <form method="get" class="p-3" autocomplete="off">
                {{ filter.form|crispy }}
                <div class="d-flex">
                  <a href="{% url 'anuncios:anuncio_report' %}" class="btn btn-outline-secondary flex-fill me-2">Limpar</a>
                  <button type="submit" class="btn btn-secondary flex-fill">Aplicar filtro</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card-body mx-4">
    {% if anuncio_list.exists %}
      <div class="table-responsive">
        <table id="tableReport" class="table responsive">
          <thead>
            <tr>
              <th scope="col">Anúncio</th>
              <th scope="col">Total investido (R$)</th>
              <th scope="col">Visualizações</th>
              <th scope="col">Cliques</th>
              <th scope="col">Compartilhamentos</th>
            </tr>
          </thead>
          <tbody>
            {% for anuncio in anuncio_list %}
            <tr>
              <th scope="row">{{ anuncio.nome|truncatechars:40 }}</th>
              <td>{{ anuncio.total_investido|intcomma }}</td>
              <td>{{ anuncio.visualizacoes|intcomma }}</td>
              <td>{{ anuncio.cliques|intcomma }}</td>
              <td>{{ anuncio.compartilhamentos|intcomma }}</td>
            </tr>
            {% endfor %}
          </tbody>
          <tfoot>
            <tr>
              <th scope="col">Total Geral</th>
              <td scope="col">{{ total_geral.investido|intcomma }}</td>
              <td scope="col">{{ total_geral.visualizacoes|intcomma }}</td>
              <td scope="col">{{ total_geral.cliques|intcomma }}</td>
              <td scope="col">{{ total_geral.compartilhamentos|intcomma }}</td>
            </tr>
          </tfoot>
        </table>
      </td>
    {% else %}
      <p class="text-center text-muted">Nenhum anúncio encontrado.</p>
    {% endif %}
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/inputmask.min.js' %}"></script>
  <script src="{% static 'anuncios/js/app.js' %}"></script>
{% endblock javascript %}

gerenciador/anuncios/templates/anuncios/anuncio_update.html
{% extends "base_site.html" %}

{% load static %}

{% block title %}Editar anúncio | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="col-xl-8 mx-auto">
    <div class="card">
      <form method="post">
        {% csrf_token %}
        <div class="card-header p-4">
          <h1>Editar Anúncio</h1>
        </div>
        <div class="card-body mx-4">
          {% include 'anuncios/_anuncio_form_fields.html' %}
        </div>
        <div class="card-footer d-flex flex-column flex-md-row p-4">
          <input class="btn btn-primary order-2" type="submit" value="Salvar Alterações">
          <a class="btn btn-link d-none d-md-block me-auto order-1" href="{{ view.get_success_url }}">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/inputmask.min.js' %}"></script>
  <script src="{% static 'anuncios/js/app.js' %}"></script>
{% endblock javascript %}

gerenciador/anuncios/templates/anuncios/cliente_create.html
{% extends "base_site.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Cadastrar cliente | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="col-xl-8 mx-auto">
    <div class="card">
      <form method="post">
        {% csrf_token %}
        <div class="card-header p-4">
          <h1>Cadastrar Cliente</h1>
        </div>
        <div class="card-body mx-4">
          {{ form|crispy }}
        </div>
        <div class="card-footer d-flex flex-column flex-md-row p-4">
          <button class="btn btn-primary ms-md-2 order-md-3" type="submit">Salvar</button>
          <button class="btn btn-outline-primary mt-2 mt-md-0 order-md-2"
                  type="submit" name="btn_salvar_e_adicionar_outro">Salvar e adicionar outro</button>
          <a class="btn btn-link d-none d-md-block me-auto order-md-1" href="{% url 'anuncios:cliente_list' %}">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

gerenciador/anuncios/templates/anuncios/cliente_detail.html
{% extends "base_site.html" %}

{% load static %}
{% load django_tables2 %}
{% load verbose_name from anuncios_tags %}

{% block title %}Detalhes do cliente | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="col mb-3">
    <div class="card">
      <div class="card-header p-4">
        <div class="d-flex flex-column flex-lg-row align-items-md-end mx-4">
          <h1 class="card-title me-auto">Detalhes do cliente</h1>
          <div class="d-flex">
            <div class="flex-fill">
              <a class="btn btn-light btn-block" href="{% url 'anuncios:cliente_list' %}">
                <i class="bi bi-arrow-left" aria-hidden="true"></i>
                <span>Voltar</span>
              </a>
              <button class="btn btn-outline-danger mx-2" type="button" data-bs-toggle="modal" data-bs-target="#modalDelete"
                data-bs-url="{% url 'anuncios:cliente_delete' cliente.pk %}"
                data-bs-model="{{ cliente|verbose_name }}" data-bs-object="{{ cliente }}">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                </svg>
              </button>
              <a class="btn btn-primary btn-block" href="{% url 'anuncios:cliente_update' cliente.pk %}">
                <i class="bi bi-pencil-square"></i>
                <span>Editar</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body mx-4">
        <table class="table table-sm">
          <tbody>
            <tr>
              <th>Nome</th>
              <td>{{ cliente.nome }}</td>
            </tr>
          </tbody>
        </table>
        <div class="py-4">
          <h3>Anúncios</h3>
          <div>
          	{% render_table table %}
          </div>
        </div>
      </div>
    </div>
    {% include "includes/modal_confirm_delete.html" %}
  </div>
{% endblock content %}

{% block javascript %}
  {{ block.super }}
  <script src="{% static 'js/modalDelete.js' %}"></script>
{% endblock javascript %}

gerenciador/anuncios/templates/anuncios/cliente_list.html
{% extends "base_site.html" %}

{% load static %}
{% load django_tables2 %}
{% load crispy_forms_tags %}

{% block title %}Lista de clientes | {{ block.super }}{% endblock %}

{% block content %}
  {% if existem_objetos_cadastrados %}
    <div class="card">
      <div class="card-header p-4">
        <div class="d-flex flex-column flex-lg-row align-items-md-end mx-4">
          <h1 class="card-title me-auto">Clientes</h1>
          <div class="d-flex">
            <div class="flex-fill">
              <a class="btn btn-primary btn-block" href="{% url 'anuncios:cliente_create' %}">
                <i class="bi bi-plus-lg" aria-hidden="true"></i>
                <span>Novo Cliente</span>
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="card-body mx-4">{% render_table table %}</div>
    </div>
  {% else %}
    <div class="p-5 mb-5 bg-transparent text-center">
      <div class="container-fluid py-5">
        <h2 class="jumbotron-heading">Cadastre um novo cliente</h2>
        <p class="lead text-muted">Está meio vazio aqui... Clique no botão abaixo para cadastrar seu 1º cliente.</p>
        <a class="btn btn-primary" href="{% url 'anuncios:cliente_create' %}">
          <i class="bi bi-plus-lg" aria-hidden="true"></i>
          <span>Novo cliente</span>
        </a>
      </div>
    </div>
  {% endif %}

{% endblock content %}

gerenciador/anuncios/templates/anuncios/cliente_update.html
{% extends "base_site.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}Editar cliente | {{ block.super }}{% endblock title %}

{% block content %}
  <div class="col-xl-8 mx-auto">
    <div class="card">
      <form method="post">
        {% csrf_token %}
        <div class="card-header p-4">
          <h1>Editar Cliente</h1>
        </div>
        <div class="card-body mx-4">
          {{ form|crispy }}
        </div>
        <div class="card-footer d-flex flex-column flex-md-row p-4">
          <input class="btn btn-primary order-2" type="submit" value="Salvar Alterações">
          <a class="btn btn-link d-none d-md-block me-auto order-1" href="{{ view.get_success_url }}">Cancelar</a>
        </div>
      </form>
    </div>
  </div>
{% endblock content %}